Include libffi-dev dependency for Ubuntu
I've just installed WeasyPrint 0.17 on Ubuntu 12.10. It required first installing libffi-dev. (I haven't checked if this also applies to other Ubuntu and Debian versions.)

Without libffi-dev pip install WeasyPrint aborted with this message:

  Installing collected packages: cffi, cairocffi, Pyphen, pycparser
    Running setup.py install for cffi
      Package libffi was not found in the pkg-config search path.
      Perhaps you should add the directory containing `libffi.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'libffi' found
      Package libffi was not found in the pkg-config search path.
      Perhaps you should add the directory containing `libffi.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'libffi' found
      Package libffi was not found in the pkg-config search path.
      Perhaps you should add the directory containing `libffi.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'libffi' found
      Package libffi was not found in the pkg-config search path.
      Perhaps you should add the directory containing `libffi.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'libffi' found
      Package libffi was not found in the pkg-config search path.
      Perhaps you should add the directory containing `libffi.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'libffi' found
      building '_cffi_backend' extension
      gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-x86_64-2.7/c/_cffi_backend.o
      c/_cffi_backend.c:14:17: fatal error: ffi.h: No such file or directory
      compilation terminated.
      error: command 'gcc' failed with exit status 1
      Complete output from command /usr/bin/python -c "import setuptools;__file__='/home/smylers/pending/WeasyPrint/build/cffi/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-R3Sp23-record/install-record.txt:
      Package libffi was not found in the pkg-config search path.

  Perhaps you should add the directory containing `libffi.pc'

  to the PKG_CONFIG_PATH environment variable

  No package 'libffi' found

  Package libffi was not found in the pkg-config search path.

  Perhaps you should add the directory containing `libffi.pc'

  to the PKG_CONFIG_PATH environment variable

  No package 'libffi' found

  Package libffi was not found in the pkg-config search path.

  Perhaps you should add the directory containing `libffi.pc'

  to the PKG_CONFIG_PATH environment variable

  No package 'libffi' found

  Package libffi was not found in the pkg-config search path.

  Perhaps you should add the directory containing `libffi.pc'

  to the PKG_CONFIG_PATH environment variable

  No package 'libffi' found

  Package libffi was not found in the pkg-config search path.

  Perhaps you should add the directory containing `libffi.pc'

  to the PKG_CONFIG_PATH environment variable

  No package 'libffi' found

  running install

  running build

  running build_py

  running build_ext

  building '_cffi_backend' extension

  gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-x86_64-2.7/c/_cffi_backend.o

  c/_cffi_backend.c:14:17: fatal error: ffi.h: No such file or directory

  compilation terminated.

  error: command 'gcc' failed with exit status 1

  ----------------------------------------
  Command /usr/bin/python -c "import setuptools;__file__='/home/smylers/pending/WeasyPrint/build/cffi/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-R3Sp23-record/install-record.txt failed with error code 1 in /home/smylers/pending/WeasyPrint/build/cffi